// Code generated by gen/gen_test.go DO NOT EDIT.

package namesilo

import (
	"encoding/xml"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func assertXMLEqual(t *testing.T, model any, fixture string) {
	t.Helper()

	expected, err := os.ReadFile(filepath.FromSlash(fixture))
	require.NoError(t, err)

	err = xml.Unmarshal(expected, model)
	require.NoError(t, err)

	raw, err := xml.MarshalIndent(model, "", "    ")
	require.NoError(t, err)

	// Fix self-closing tags.
	exp, err := regexp.Compile("<(\\w+)></\\w+>")
	require.NoError(t, err)

	raw = exp.ReplaceAll(raw, []byte("<$1/>"))

	if toCleanString(raw) != toCleanString(expected) {
		t.Logf("Got:\n%s\n\nWant:\n%s\n", string(raw), string(expected))
		t.Error("Errors")
	}
}

func toCleanString(data []byte) string {
	return strings.TrimSuffix(strings.ReplaceAll(string(data), "\r\n", "\n"), "\n")
}

func TestAddAccountFunds(t *testing.T) {
	assertXMLEqual(t, &AddAccountFunds{}, "./fixtures/account/addAccountFunds.xml")
}

func TestAddAutoRenewal(t *testing.T) {
	assertXMLEqual(t, &AddAutoRenewal{}, "./fixtures/domains/addAutoRenewal.xml")
}

func TestAddPrivacy(t *testing.T) {
	assertXMLEqual(t, &AddPrivacy{}, "./fixtures/privacy/addPrivacy.xml")
}

func TestAddRegisteredNameServer(t *testing.T) {
	assertXMLEqual(t, &AddRegisteredNameServer{}, "./fixtures/nameserver/addRegisteredNameServer.xml")
}

func TestBidAuction(t *testing.T) {
	assertXMLEqual(t, &BidAuction{}, "./fixtures/auctions/bidAuction.xml")
}

func TestBuyNowAuction(t *testing.T) {
	assertXMLEqual(t, &BuyNowAuction{}, "./fixtures/auctions/buyNowAuction.xml")
}

func TestChangeNameServers(t *testing.T) {
	assertXMLEqual(t, &ChangeNameServers{}, "./fixtures/nameserver/changeNameServers.xml")
}

func TestCheckRegisterAvailability(t *testing.T) {
	assertXMLEqual(t, &CheckRegisterAvailability{}, "./fixtures/domains/checkRegisterAvailability.xml")
}

func TestCheckTransferAvailability(t *testing.T) {
	assertXMLEqual(t, &CheckTransferAvailability{}, "./fixtures/domains/checkTransferAvailability.xml")
}

func TestCheckTransferStatus(t *testing.T) {
	assertXMLEqual(t, &CheckTransferStatus{}, "./fixtures/transfers/checkTransferStatus.xml")
}

func TestConfigureEmailForward(t *testing.T) {
	assertXMLEqual(t, &ConfigureEmailForward{}, "./fixtures/email/configureEmailForward.xml")
}

func TestContactAdd(t *testing.T) {
	assertXMLEqual(t, &ContactAdd{}, "./fixtures/contact/contactAdd.xml")
}

func TestContactDelete(t *testing.T) {
	assertXMLEqual(t, &ContactDelete{}, "./fixtures/contact/contactDelete.xml")
}

func TestContactDomainAssociate(t *testing.T) {
	assertXMLEqual(t, &ContactDomainAssociate{}, "./fixtures/contact/contactDomainAssociate.xml")
}

func TestContactList(t *testing.T) {
	assertXMLEqual(t, &ContactList{}, "./fixtures/contact/contactList.xml")
}

func TestContactUpdate(t *testing.T) {
	assertXMLEqual(t, &ContactUpdate{}, "./fixtures/contact/contactUpdate.xml")
}

func TestCountExpiringDomains(t *testing.T) {
	assertXMLEqual(t, &CountExpiringDomains{}, "./fixtures/account/countExpiringDomains.xml")
}

func TestDeleteEmailForward(t *testing.T) {
	assertXMLEqual(t, &DeleteEmailForward{}, "./fixtures/email/deleteEmailForward.xml")
}

func TestDeleteRegisteredNameServer(t *testing.T) {
	assertXMLEqual(t, &DeleteRegisteredNameServer{}, "./fixtures/nameserver/deleteRegisteredNameServer.xml")
}

func TestDnsAddRecord(t *testing.T) {
	assertXMLEqual(t, &DnsAddRecord{}, "./fixtures/dns/dnsAddRecord.xml")
}

func TestDnsDeleteRecord(t *testing.T) {
	assertXMLEqual(t, &DnsDeleteRecord{}, "./fixtures/dns/dnsDeleteRecord.xml")
}

func TestDnsListRecords(t *testing.T) {
	assertXMLEqual(t, &DnsListRecords{}, "./fixtures/dns/dnsListRecords.xml")
}

func TestDnsSecAddRecord(t *testing.T) {
	assertXMLEqual(t, &DnsSecAddRecord{}, "./fixtures/dns/dnsSecAddRecord.xml")
}

func TestDnsSecDeleteRecord(t *testing.T) {
	assertXMLEqual(t, &DnsSecDeleteRecord{}, "./fixtures/dns/dnsSecDeleteRecord.xml")
}

func TestDnsSecListRecords(t *testing.T) {
	assertXMLEqual(t, &DnsSecListRecords{}, "./fixtures/dns/dnsSecListRecords.xml")
}

func TestDnsUpdateRecord(t *testing.T) {
	assertXMLEqual(t, &DnsUpdateRecord{}, "./fixtures/dns/dnsUpdateRecord.xml")
}

func TestDomainForward(t *testing.T) {
	assertXMLEqual(t, &DomainForward{}, "./fixtures/domains/domainForward.xml")
}

func TestDomainForwardSubDomain(t *testing.T) {
	assertXMLEqual(t, &DomainForwardSubDomain{}, "./fixtures/domains/domainForwardSubDomain.xml")
}

func TestDomainForwardSubDomainDelete(t *testing.T) {
	assertXMLEqual(t, &DomainForwardSubDomainDelete{}, "./fixtures/domains/domainForwardSubDomainDelete.xml")
}

func TestDomainLock(t *testing.T) {
	assertXMLEqual(t, &DomainLock{}, "./fixtures/domains/domainLock.xml")
}

func TestDomainUnlock(t *testing.T) {
	assertXMLEqual(t, &DomainUnlock{}, "./fixtures/domains/domainUnlock.xml")
}

func TestEmailVerification(t *testing.T) {
	assertXMLEqual(t, &EmailVerification{}, "./fixtures/email/emailVerification.xml")
}

func TestGetAccountBalance(t *testing.T) {
	assertXMLEqual(t, &GetAccountBalance{}, "./fixtures/account/getAccountBalance.xml")
}

func TestGetDomainInfo(t *testing.T) {
	assertXMLEqual(t, &GetDomainInfo{}, "./fixtures/domains/getDomainInfo.xml")
}

func TestGetPrices(t *testing.T) {
	assertXMLEqual(t, &GetPrices{}, "./fixtures/domains/getPrices.xml")
}

func TestListAuctions(t *testing.T) {
	assertXMLEqual(t, &ListAuctions{}, "./fixtures/auctions/listAuctions.xml")
}

func TestListDomains(t *testing.T) {
	assertXMLEqual(t, &ListDomains{}, "./fixtures/domains/listDomains.xml")
}

func TestListEmailForwards(t *testing.T) {
	assertXMLEqual(t, &ListEmailForwards{}, "./fixtures/email/listEmailForwards.xml")
}

func TestListExpiringDomains(t *testing.T) {
	assertXMLEqual(t, &ListExpiringDomains{}, "./fixtures/account/listExpiringDomains.xml")
}

func TestListOrders(t *testing.T) {
	assertXMLEqual(t, &ListOrders{}, "./fixtures/account/listOrders.xml")
}

func TestListRegisteredNameServers(t *testing.T) {
	assertXMLEqual(t, &ListRegisteredNameServers{}, "./fixtures/nameserver/listRegisteredNameServers.xml")
}

func TestMarketplaceActiveSalesOverview(t *testing.T) {
	assertXMLEqual(t, &MarketplaceActiveSalesOverview{}, "./fixtures/marketplace/marketplaceActiveSalesOverview.xml")
}

func TestMarketplaceAddOrModifySale(t *testing.T) {
	assertXMLEqual(t, &MarketplaceAddOrModifySale{}, "./fixtures/marketplace/marketplaceAddOrModifySale.xml")
}

func TestMarketplaceLandingPageUpdate(t *testing.T) {
	assertXMLEqual(t, &MarketplaceLandingPageUpdate{}, "./fixtures/marketplace/marketplaceLandingPageUpdate.xml")
}

func TestModifyRegisteredNameServer(t *testing.T) {
	assertXMLEqual(t, &ModifyRegisteredNameServer{}, "./fixtures/nameserver/modifyRegisteredNameServer.xml")
}

func TestOrderDetails(t *testing.T) {
	assertXMLEqual(t, &OrderDetails{}, "./fixtures/account/orderDetails.xml")
}

func TestPortfolioAdd(t *testing.T) {
	assertXMLEqual(t, &PortfolioAdd{}, "./fixtures/portfolio/portfolioAdd.xml")
}

func TestPortfolioDelete(t *testing.T) {
	assertXMLEqual(t, &PortfolioDelete{}, "./fixtures/portfolio/portfolioDelete.xml")
}

func TestPortfolioDomainAssociate(t *testing.T) {
	assertXMLEqual(t, &PortfolioDomainAssociate{}, "./fixtures/portfolio/portfolioDomainAssociate.xml")
}

func TestPortfolioList(t *testing.T) {
	assertXMLEqual(t, &PortfolioList{}, "./fixtures/portfolio/portfolioList.xml")
}

func TestRegisterDomain(t *testing.T) {
	assertXMLEqual(t, &RegisterDomain{}, "./fixtures/domains/registerDomain.xml")
}

func TestRegisterDomainDrop(t *testing.T) {
	assertXMLEqual(t, &RegisterDomainDrop{}, "./fixtures/domains/registerDomainDrop.xml")
}

func TestRegistrantVerificationStatus(t *testing.T) {
	assertXMLEqual(t, &RegistrantVerificationStatus{}, "./fixtures/email/registrantVerificationStatus.xml")
}

func TestRemoveAutoRenewal(t *testing.T) {
	assertXMLEqual(t, &RemoveAutoRenewal{}, "./fixtures/domains/removeAutoRenewal.xml")
}

func TestRemovePrivacy(t *testing.T) {
	assertXMLEqual(t, &RemovePrivacy{}, "./fixtures/privacy/removePrivacy.xml")
}

func TestRenewDomain(t *testing.T) {
	assertXMLEqual(t, &RenewDomain{}, "./fixtures/domains/renewDomain.xml")
}

func TestRetrieveAuthCode(t *testing.T) {
	assertXMLEqual(t, &RetrieveAuthCode{}, "./fixtures/transfers/retrieveAuthCode.xml")
}

func TestTransferDomain(t *testing.T) {
	assertXMLEqual(t, &TransferDomain{}, "./fixtures/transfers/transferDomain.xml")
}

func TestTransferUpdateChangeEPPCode(t *testing.T) {
	assertXMLEqual(t, &TransferUpdateChangeEPPCode{}, "./fixtures/transfers/transferUpdateChangeEPPCode.xml")
}

func TestTransferUpdateResendAdminEmail(t *testing.T) {
	assertXMLEqual(t, &TransferUpdateResendAdminEmail{}, "./fixtures/transfers/transferUpdateResendAdminEmail.xml")
}

func TestTransferUpdateResubmitToRegistry(t *testing.T) {
	assertXMLEqual(t, &TransferUpdateResubmitToRegistry{}, "./fixtures/transfers/transferUpdateResubmitToRegistry.xml")
}

func TestViewAuction(t *testing.T) {
	assertXMLEqual(t, &ViewAuction{}, "./fixtures/auctions/viewAuction.xml")
}

func TestViewAuctionHistory(t *testing.T) {
	assertXMLEqual(t, &ViewAuctionHistory{}, "./fixtures/auctions/viewAuctionHistory.xml")
}

func TestWatchAuction(t *testing.T) {
	assertXMLEqual(t, &WatchAuction{}, "./fixtures/auctions/watchAuction.xml")
}

func TestWhoisInfo(t *testing.T) {
	assertXMLEqual(t, &WhoisInfo{}, "./fixtures/domains/whoisInfo.xml")
}
